# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d35aad882a595695397791f4b92877b8d466a2c84411f6829bf896659961ca677f3fffc5b902a5bf1d32fa686a75be104996494b9345953883573456feb22cb8

test:
  secret_key_base: f46e3139d3cce7bd2ed5e295878ad67af427e8a8374879b223c4bbe6b621367c947b5d32c1661d627adb771b8b03a0ebf3c330c8e82e11b4f8d21936039a0757

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
